In [1]:
import ReadRawMHD as rR
import mapping as mapp
import numpy as np
import matplotlib.pyplot as plt
import SimpleITK as sitk
import time
import os
t1 = time.time()

In [2]:
# # # # # Input # # # # #
# Input imaging data
models = ['00_L50_S50_D30', '01_L50_S50_D35', '02_L50_S50_D40', '10_L50_S00_D30', '11_L50_S00_D35', '12_L50_S00_D40']
model_code = models[5]  # FEA model name
sample_code = '03_Pilot3'  # Experimental sample. contains number and sample name, e.g. 00_Pilot3.
ExpScrew = 'T'  # T or P, site from experiment. Two input files (SimScrew Ti and PEEK) will be generated for each site
file_bone = 'XCT_Icotec_S130672_L5_intact_planned.mhd'  # gray value bone ct scan, gauss filter applied
file_inst = 'ICOTEC_S130672_L5_implants_XCTres.mhd'  # segmented screw scan

In [3]:
# Specify file locations
#---sample_no, sample = sample_code.split('_')  # sample name and number
path_project = '/home/biomech/Documents/01_Icotec/'  # General project folder
path_ct = path_project + '01_Experiments/02_Scans/' + sample_code + '/04_Registered/'  # Folder of CT data
path_fea = path_project + '02_FEA/98_Pilots/' + sample_code + '/' + model_code + '/'  # Folder of FEA files
# Include general path for mesh/template later
info = sample_code + ExpScrew + '_info.txt'  # .txt file containing info about landmarks. Specific structure

In [4]:
# # # # # Input # # # # #
# Input FEA data
Input = {}
Input['Project_Folder'] = path_project
Input['FEA_loc'] = path_fea  # path to FEA files
Input['Model_Code'] = model_code  # model code (FEA model name)
Input['Screw'] = ExpScrew  # which site of scan will be processed
Input['Resolution'] = 0.0607  # scan resolution, should be 0.0607

Input['F_dir'] = '-'  # force direction (negative corresponds to experiment). Input '-' or '+'
Input['F_max'] = 150  # peak load
Input['F_min'] = 10  # valley load, not included yet
Input['Cycles'] = 2  # how many cycles to simulate, not included yet
Input['Friction'] = 0.2  # friction between screw and bone, not included yet
Input['ElType'] = 'Quadratic'  # element type quadratic or linear C3D8 = linear, not included yet
Input['Mapping_Diameter'] = 2.5  # diameter of sphere for mapping, in mm. should be larger than element size

# parametrise screw length? --> different mesh sizes
# parametrise ROI?
# parametrise step size?

# Submit on cortex or ubelix?
# Parameters as e-mail, runtime, memory etc. can be changed in the template file
Input['Submit'] = 'cortex'
mapp.write_submit(Input)

# Write output images? segmented image and mask, for visual check
write_output = 0

In [5]:
# Write mesh input file
mapp.write_mesh(Input)  # Original input file, path for mesh.inp
#--> template, ???

Finished extracting mesh file.


In [6]:
# Load data
imD = rR.load_itk(path_ct + file_inst)  # screw image
with open(path_ct + info, 'r') as f:
    content = f.read()
ori = content.split('Origin: ')[1].split('\n')[0]
ori = np.array([int(ori.split(' ')[0]), int(ori.split(' ')[1]), int(ori.split(' ')[2])])
p1P = content.split('positive x axis: ')[1].split('\n')[0]
p1P = np.array([int(p1P.split(' ')[0]), int(p1P.split(' ')[1]), int(p1P.split(' ')[2])])
p1N = content.split('negative x axis: ')[1].split('\n')[0]
p1N = np.array([int(p1N.split(' ')[0]), int(p1N.split(' ')[1]), int(p1N.split(' ')[2])])

In [7]:
# # # # # Input # # # # #
# Define screw vector
v3 = []
if ExpScrew == 'T':
    lineT = rR.axis3D(imD[0], 670, 1100, 'x')  # if starting from screw tip towards head, add (-) to v3
    v3 = -lineT.vector  # z-axis = screw axis, found by function. Specify +/-!!
elif ExpScrew == 'P':
    lineT = rR.axis3D(imD[0], 0, 600, 'x')  # if starting from screw tip towards head, add (-) to v3
    v3 = lineT.vector  # z-axis = screw axis, found by function. Specify +/-!!
del imD

In [8]:
# Compute matrix
v2 = np.cross(v3, p1P-p1N)/np.linalg.norm(np.cross(v3, p1P-p1N))  # y-axis
v1 = np.cross(v2, v3)  # x-axis
M = np.vstack((np.append(v1, ori[0]), np.append(v2, ori[1]), np.append(v3, ori[2]), np.array([0, 0, 0, 1])))
print(M)

[[-7.93273539e-01 -1.31847220e-02  6.08722643e-01  1.08500000e+03]
 [ 2.21123987e-02  9.98482113e-01  5.04431538e-02  4.52000000e+02]
 [-6.08463749e-01  5.34755369e-02 -7.91777893e-01  7.05000000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [9]:
# Check coordinate system
# z-axis (blue) should point from screw head (origin) towards screw tip (dot)
# y-axis (green) should be perpendicular to screw-rotAxis plane and point upwards (against loading direction)
# x-axis (red): right-handed coordinate system
%matplotlib notebook
plt.figure()
ax = plt.axes(projection='3d')
fact = 100
for i in range(-0, 5):
    ax.scatter3D(ori[0]+i*fact*v1[0], ori[1]+i*fact*v1[1], ori[2]+i*fact*v1[2], c='r', alpha=1)
    ax.scatter3D(ori[0]+i*fact*v2[0], ori[1]+i*fact*v2[1], ori[2]+i*fact*v2[2], c='g', alpha=1)
    ax.scatter3D(ori[0]+i*fact*v3[0], ori[1]+i*fact*v3[1], ori[2]+i*fact*v3[2], c='b', alpha=1)
ax.scatter3D(p1P[0], p1P[1], p1P[2], c='b')
ax.scatter3D([0, 1500], [0, 1500], [0, 1500], alpha=0)
ax.scatter3D(686, 480, 177, c='k', alpha=1)  # Ti tip
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()

<IPython.core.display.Javascript object>

In [10]:
bone = {}

In [11]:
bone = mapp.readInpBoneDummy(bone, Input)  # Read bone mesh from abaqus. Read elements, nodes

In [12]:
bone = mapp.boneMeshMask(bone, Input)  # Create mask from abaqus bone mesh

BoneMeshMask


In [13]:
bone = mapp.load_BVTVdata(bone, path_ct + file_bone)

In [14]:
# Read mask
imMask = sitk.ReadImage(Input['FEA_loc'] + Input['Model_Code'] + Input['Screw'] + '_mask.mhd')
imMask_np = np.transpose(sitk.GetArrayFromImage(imMask), [2, 1, 0])
bone["GreyImage"].SetOrigin([0, 0, 0])
# Define rotation and translation
[theta1, theta2, theta3] = rR.rotation_angles_from_matrix(M[:3, :3], 'zyx')
theta2 = -theta2 + np.pi  # +pi because arc-tan has no unique solution. WHY NEGATIVE, because mask[:, ::, :] reshaped?
center = np.array([imMask_np.shape[0]/2, imMask_np.shape[1]/2, 0]) * imMask.GetSpacing()
trans = M[:3, 3] * imMask.GetSpacing() - center

In [15]:
# Write transformation file
f = open(path_fea + 'transformation_' + model_code + ExpScrew + '.tfm', "w")
f.write(
    "#Insight Transform File V1.0\n"
    "#Transform 0\n"
    "Transform: CompositeTransform_double_3_3\n"
    "#Transform 1\n"
    "Transform: Euler3DTransform_double_3_3\n"
    "Parameters:  " + f'{theta1}' + " " + f'{theta2}' + " " + f'{theta3}'
    + " " + f'{trans[0]}' + " " + f'{trans[1]}' + " " + f'{trans[2]}' + "\n"  # transformation
    "FixedParameters: " + f'{center[0]}' + " " + f'{center[1]}' + " " + f'{center[2]}' + " 0\n")  # CoR
f.close()

In [16]:
# Apply transformation to mask using the inverse transformation
bone['Transform'] = sitk.ReadTransform(path_fea + 'transformation_' + model_code + ExpScrew + '.tfm')
bone['Transform_inv'] = bone['Transform'].GetInverse()
imMask_trans = sitk.Resample(imMask, bone['GreyImage'], bone['Transform_inv'], sitk.sitkNearestNeighbor, 0.0, bone['GreyImage'].GetPixelID())
# Delete some files / variables to save memory
os.remove(path_fea + model_code + ExpScrew + '_mask.mhd')
os.remove(path_fea + model_code + ExpScrew + '_mask.raw')
if write_output:
    img_seg=sitk.GetImageFromArray(np.transpose(bone['BVTVscaled'], [2, 1, 0]))
    img_seg.SetOrigin(bone["GreyImage"].GetOrigin())
    img_seg.SetSpacing(bone["GreyImage"].GetSpacing())
    sitk.WriteImage(img_seg, path_fea+ + sample_code + '_seg.mhd')
    imMask_trans.SetOrigin(bone["GreyImage"].GetOrigin())
    imMask_trans.SetSpacing(bone["GreyImage"].GetSpacing())
    sitk.WriteImage(imMask_trans, path_fea + model_code + '_' + ExpScrew + '_maskTrans.mhd')
    del img_seg
del bone['GreyImage']

In [17]:
# BVTV segmentation / calibration HR-pQCT to uCT
bone['MASK_array_T'] = np.transpose(sitk.GetArrayFromImage(imMask_trans), [2, 1, 0])
# scaling factor/intercept from Schenk et al. 2022, has to be discussed w Ph

In [18]:
mapp.HFE_mapping_trans(bone, Input)

... start material mapping with copying boundary layers as ghost layers
 ... material mapping element 333/2680

/home/biomech/Documents/01_Icotec/04_Code/venv/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/biomech/Documents/01_Icotec/04_Code/venv/lib/python3.10/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


 ... material mapping element 2680/2680
... material mapping finished

 ... update ABAQUS files:
/home/biomech/Documents/01_Icotec/02_FEA/98_Pilots/03_Pilot3/12_L50_S00_D40/12_L50_S00_D40T_elsets.inp
and
/home/biomech/Documents/01_Icotec/02_FEA/98_Pilots/03_Pilot3/12_L50_S00_D40/12_L50_S00_D40T_materials.inp


{'elems': {1: <MedtoolFunctions.med_classes.element at 0x7f41ae955630>,
  2: <MedtoolFunctions.med_classes.element at 0x7f41ae955660>,
  3: <MedtoolFunctions.med_classes.element at 0x7f41ae955690>,
  4: <MedtoolFunctions.med_classes.element at 0x7f41ae9556c0>,
  5: <MedtoolFunctions.med_classes.element at 0x7f41ae9556f0>,
  6: <MedtoolFunctions.med_classes.element at 0x7f41ae955720>,
  7: <MedtoolFunctions.med_classes.element at 0x7f41ae955750>,
  8: <MedtoolFunctions.med_classes.element at 0x7f41ae955780>,
  9: <MedtoolFunctions.med_classes.element at 0x7f41ae9557b0>,
  10: <MedtoolFunctions.med_classes.element at 0x7f41ae9557e0>,
  11: <MedtoolFunctions.med_classes.element at 0x7f41ae955810>,
  12: <MedtoolFunctions.med_classes.element at 0x7f41ae955840>,
  13: <MedtoolFunctions.med_classes.element at 0x7f41ae955870>,
  14: <MedtoolFunctions.med_classes.element at 0x7f41ae9558a0>,
  15: <MedtoolFunctions.med_classes.element at 0x7f41ae9558d0>,
  16: <MedtoolFunctions.med_classes.elem

In [19]:
sliceNo = 460
plt.imshow(bone['BVTVscaled'][:, sliceNo, :] + bone['MASK_array_T'][:, sliceNo, :])

plt.show()

In [20]:
# Write final input file
mapp.HFE_inp_creator(Input)
if not write_output:
    os.remove(Input['FEA_loc'] + Input['Model_Code'] + Input['Screw'] + '_elsets.inp')
    os.remove(Input['FEA_loc'] + Input['Model_Code'] + Input['Screw'] + '_materials.inp')
    os.remove(Input['FEA_loc'] + Input['Model_Code'] + '_mesh.inp')
    os.remove(Input['FEA_loc'] + 'transformation_' + Input['Model_Code'] + Input['Screw'] + '.tfm')

Section set to Ti.
Section set to PEEK.
End HFE_inp_creator


In [21]:
print('Execution time: ' + str(int((time.time()-t1)/60)) + ' min '+ str(round(np.mod(time.time()-t1, 60), 1)) + ' sec.')

Execution time: 2 min 45.9 sec.
