In [27]:
import ReadRawMHD as RR
import numpy as np

In [28]:
loc = '/home/biomech/Documents/01_Icotec/01_Experiments/02_Scans/Pilot3/04_Registered/'
bone = 'XCT_Icotec_S130672_L5_intact_planned.mhd'
inst = 'ICOTEC_S130672_L5_implants_XCTres.mhd'

In [29]:
im0 = RR.load_itk(loc + bone)
imD = RR.load_itk(loc + inst)
lineT = RR.axis3D(imD[0], 670, 1100, 0, 0)

In [31]:
# p0 = np.array([764, 453, 1130])  # origin, screw shaft
p0 = np.array([1130, 453, 764])  # origin, screw shaft
# p1 = np.array([188, 471, 702])
# p1 = np.array([702, 471, 188])
# p2 = np.array([820, 474, 54])  # point on rotation axis
p2 = np.array([54, 474, 820])  # point on rotation axis
v1 = -lineT.vector
v2 = np.cross(v1, p2-p0)/np.linalg.norm(np.cross(v1, p2-p0))
v3 = np.cross(v1, v2)
rotation_matrix = np.vstack((np.append(v1, 0), np.append(v2, 0), np.append(v3, 0), np.array([0, 0, 0, 1])))
translation_matrix = np.array([[1, 0, 0, p0[0]],
                               [0, 1, 0, p0[1]],
                               [0, 0, 1, p0[2]],
                               [0, 0, 0,    1]])
COS_CT = np.dot(rotation_matrix, translation_matrix)
COS_FE = np.eye(4)
print(COS_CT)

[[-7.91777893e-01  5.34755369e-02 -6.08463749e-01 -1.33535091e+03]
 [ 2.25184329e-02  9.98038607e-01  5.84111263e-02  5.22183419e+02]
 [ 6.10393879e-01  3.25469884e-02 -7.91429091e-01  9.98370437e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
